version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DeFINITION>
        LoadBalancerInfo:
          ContainerName: "helloworld-rest"
          ContainerPort: "80"
        PlatformVersion: "LATEST"