version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:459343727810:task-definition/spring-fargate-ci:4"
        LoadBalancerInfo:
          ContainerName: "helloworld-rest"
          ContainerPort: "80"
        PlatformVersion: "LATEST"